name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build_and_e2e:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # הגנה קטנה: מפיל את הריצה אם נשארו סימני merge conflict בקבצים (כמו שהיה ב-.env)
      - name: Fail if merge conflict markers exist
        run: |
          if git grep -nE '^[<=>]{7}'; then
            echo "Resolve merge conflicts before running CI."
            exit 1
          fi

      # AWS creds ל-runner
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      # לוגין לרג'יסטרי של ECR (נדרש כדי לדחוף ולמשוך את התמונה הפרטית)
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # מביאים את ה-Account ID כדי לא לקבע מספרים בקוד (נוח גם ללוגים)
      - name: Get AWS Account ID
        id: sts
        run: echo "AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> "$GITHUB_ENV"

      # Build & Push של התמונה לתג latest (כדי שה-E2E ירוצו על מה שבנינו עכשיו)
      - name: Build & Push web image (:latest)
        run: |
          REG="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          IMAGE="${REG}/entrytracker:latest"
          echo "Building ${IMAGE}"
          docker build -t "${IMAGE}" .
          docker push "${IMAGE}"

      # E2E: מושכים את ה-image הפרטי ומרימים את הסטאק (בלי --build)
      - name: Run E2E with Docker Compose
        env:
          COMPOSE_PROJECT_NAME: entrytracker
        run: |
          # מושך מראש את ה-web (נח לקבל שגיאה מהירה אם אין הרשאות)
          docker compose pull web
          docker compose up -d      # שימי לב: בלי --build
          # בריאות בסיסית (התאימי לצורך שלך):
          # המתנה קצרה לעליית הקונטיינרים
          sleep 10
          # אפשר להחליף/להוסיף בדיקות Playwright/pytest וכו'
          curl -f http://localhost/ || (docker compose ps && docker compose logs --no-color && exit 1)
          docker compose down -v
